### ISSUE TITLE
Cannot orbit all the way around a skeleton

### ISSUE THREAD

**Issue by hubbardp** [JaneliaSciComp/SharkViewer#3]
If you move the mouse up or down to rotate the skeleton around a horizontal axis, there is a limit of 180 degrees.  This behavior seems to be a fundamental limit on the THREE.js OrbitControls:

https://discourse.threejs.org/t/solved-orbitcontrols-max-polar-angle-infinity/2629/3

That article mentions a "Trackball" control, which may or may not still be available.  If not, it is possible to write the proper control from scratch.

**Comment by neomorphic** [comment]
Fixed by @hubbardp in fa82cc8acbc82da166e509698852435c4237fd2e
