### ISSUE TITLE
Saving image to svg file

### ISSUE THREAD

**Issue by dilawar** [JaneliaSciComp/SharkViewer#6]
Is it possible to save the displayed image as svg file?

**Comment by cmbruns-hhmi** [comment]
I expect this is impossible, owing to the low-level image-based clever fragment shader rendering performed by SharkViewer.

In case I'm wrong, a good starting point might be this blog post explaining how to export a much simpler Three.js rendering to SVG:
http://blog.felixbreuer.net/2014/08/05/using-threejs-to-create-vector-graphics-from-3d-visualizations.html
Apparently Three.js has a SVGRenderer example class for this purpose.

**Comment by dilawar** [comment]
Thanks.
